WebBlog.Api/WebBlog.AuthServer/Models/RedirectViewModel.cs
namespace WebBlog.AuthServer.Models
{
    public class RedirectViewModel
    {
        public string RedirectUrl { get; set; }
    }
}

WebBlog.Api/WebBlog.AuthServer/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace WebBlog.AuthServer.Controllers
{
    [Authorize(Roles = $"{AuthServerConstants.Role.Administrator}")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            return RedirectToAction("Index");
        }
    }
}

WebBlog.Api/WebBlog.AuthServer/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebBlog.AuthServer.Models;

namespace WebBlog.AuthServer.Controllers
{
    [Authorize(Roles = $"{AuthServerConstants.Role.Administrator}")]
    public class UsersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var identityUsers = await _userManager.Users.ToListAsync();

            List<UserListViewModel.UserItemModel> userList = new();
            foreach (var user in identityUsers)
            {
                var userClaims = await _userManager.GetClaimsAsync(user);
                userList.Add(CreateUserItemModel(user, userClaims));
            }

            return View(new UserListViewModel { Users = userList });
        }

        private UserListViewModel.UserItemModel CreateUserItemModel(IdentityUser identityUser, IList<Claim> userClaims)
        {
            var createdAtClaim = userClaims.FirstOrDefault(x => x.Type == AuthServerConstants.ClaimType.CreatedAt)?.Value;
            DateTime.TryParse(createdAtClaim, out var createdAt);

            var fullName = userClaims.FirstOrDefault(x => x.Type == AuthServerConstants.ClaimType.FullName)?.Value;

            return new UserListViewModel.UserItemModel
            {
                FullName = fullName,
                UserName = identityUser.UserName,
                UserId = identityUser.Id,
                CreatedAt = createdAt
            };
        }

        public async Task<IActionResult> Update(string userId)
        {
            var userIdentity = await _userManager.FindByIdAsync(userId);
            var userClaims = await _userManager.GetClaimsAsync(userIdentity);
            var userRoles = await _userManager.GetRolesAsync(userIdentity);
            
            var selectableRoles = await _roleManager.Roles.ToListAsync();
            var userInfo = CreateUserItemModel(userIdentity, userClaims);
            
            var userDetailViewModel = new UserDetailViewModel
            {
                UserId = userInfo.UserId,
                FullName = userInfo.FullName,
                UserName = userInfo.UserName,
                CreatedAt = userInfo.CreatedAt,
            };

            userDetailViewModel.RoleIds = userRoles;
            userDetailViewModel.SelectableRoleList = selectableRoles.Select(x => x.Name).ToList();

            return View(userDetailViewModel);
        }
    }
}

WebBlog.Api/WebBlog.AuthServer/Views/Shared/Redirect.cshtml
@model RedirectViewModel

<h1>You are now being returned to the application.</h1>
<p>Once complete, you may close this tab</p>

<meta http-equiv="refresh" content="0;url=@Model.RedirectUrl" data-url="@Model.RedirectUrl">
<script src="~/js/signin-redirect.js"></script>

WebBlog.Api/WebBlog.AuthServer/Views/Shared/_Layout.cshtml
@using IdentityServer4.Extensions
@{
    string name = null;
    if (!true.Equals(ViewData["signed-out"]))
    {
        name = Context.User?.GetDisplayName();
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IdentityServer4</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/">
                    <span class="navbar-brand">
                        <img src="~/icon.png" class="icon-banner">IdentityServer4
                    </span>
                </a>
            </div>

            @if (User.IsInRole(AuthServerConstants.Role.Administrator))
            {
               <ul class="nav navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Users">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Roles">Roles</a>
                </li>
            </ul>
            }
            
            @if (!string.IsNullOrWhiteSpace(name))
            {
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">@name <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-action="Logout" asp-controller="Account">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            }
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

WebBlog.Api/WebBlog.AuthServer/Views/Shared/_ValidationSummary.cshtml
@if (ViewContext.ModelState.IsValid == false)
{
    <div class="alert alert-danger">
        <strong>Error</strong>
        <div asp-validation-summary="All" class="danger"></div>
    </div>
}